name: Lint
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tflint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
      name: Checkout source code

    - uses: actions/cache@v3
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v4
      name: Setup TFLint
      with:
        tflint_version: v0.49.0

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --recursive --init
      env:
        # https://github.com/terraform-linters/tflint/blob/master/docs/user-guide/plugins.md#avoiding-rate-limiting
        GITHUB_TOKEN: ${{ github.token }}

    - name: Change directory
      run: cd ./prod/services/webserver-cluster

    - name: list contents of directory
      run: ls -la

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AK }}
        aws-secret-access-key: ${{ secrets.SAK }}
        aws-region: eu-west-2

    - name: Terraform init
      run: terraform -chdir=./prod/services/webserver-cluster init

    - name: Terraform init
      run: terraform init

    - name: Run TFLint Now
      run: tflint --recursive --call-module-type=all -f compact
    
    #- uses: terraform-linters/setup-tflint@v3
      #with:
      #  tflint_wrapper: true
    
    #- id: tflint
    #  run: tflint -f compact

    #- run: echo hi!
    #- run: echo ${{ steps.tflint.outputs.stdout }}
    #- run: echo ${{ steps.tflint.outputs.stderr }}
    #- run: echo ${{ steps.tflint.outputs.exitcode }}